// <auto-generated />
using FoodBank.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodBank.Migrations
{
    [DbContext(typeof(FoodBankContext))]
    partial class FoodBankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("FoodBank.Models.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Calories");

                    b.Property<string>("Item_Name");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("FoodItem");
                });
#pragma warning restore 612, 618
        }
    }
}
